// applicaion text constants
export const ConstantText = {
  toast_success: 'success',
  toast_error: 'error',
  toast_connected: 'Device Connected.',
  toast_bottom: 'bottom',
  coffee_machine_title: 'Dark Roasted Beans',
  coffee_machine_subTitle: 'Tap the machine to start',
  coffee_device_id_title: 'Brew with Lex',
  coffee_types_subTitle: 'Select your style',
  font_family: 'Avenir',
  font_family2: 'Avenir Next',
  font_bold1: '500',
  font_bold2: '600',
  font_bold3: '700',
  network_failure: 'Network request failed',
  coffee_ristretto: 'Ristretto',
  coffee_cappuccino: 'Cappuccino',
  coffee_espresso: 'Espresso',
};
